# Generated by Django 3.1.2 on 2020-10-29 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricechecker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
